using System;
System.Console.Write("Type 1st Number:");
int firstNum = Convert.ToInt32(Console.ReadLine());
System.Console.Write("Type 2nd Number:");
int secondNum = Convert.ToInt32(Console.ReadLine());
System.Console.WriteLine($"1st number is greater than 2nd number:{firstNum>secondNum}");
System.Console.WriteLine($"1st number is smaller than 2nd number:{firstNum<secondNum}");
System.Console.WriteLine($"1st number and 2nd number are equal:{firstNum==secondNum}");
System.Console.WriteLine($"1st number and 2nd number are not equal:{firstNum!=secondNum}");
System.Console.WriteLine($"1st number is greater than or equal 2nd number:{firstNum>=secondNum}");
System.Console.WriteLine($"1st number is smaller than or equal 2nd number:{firstNum<=secondNum}");
